import type { Metadata } from "next";
import Link from "next/link";
import { COURSES } from "./courses/courses";
import { CourseCard } from "@/components/CourseCard";
import { LessonFigure } from "@/components/LessonFigure";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

export const metadata: Metadata = { alternates: { canonical: "/" } };

export default function HomePage() {
  const topics = new Set(COURSES.map((course) => course.topic)).size;
  return <><SiteHeader /><main id="main-content"><section className="editorial-hero"><div><p className="eyebrow">Structured digital learning</p><h1>Learn useful technology through clear, practical lessons.</h1><p>DigiLearn brings together {COURSES.length} courses across {topics} topic areas. Read focused lessons, test your understanding, keep personal notes and return to genuine progress saved on your device.</p><div className="hero-actions"><Link className="button primary inline-button" href="/courses">Explore all courses</Link><Link className="text-link" href="/practice">Open practice decks →</Link></div><p className="access-notice"><strong>Free learning access:</strong> Every course is currently open. Previously paid courses show their honest future KES price, but no payment is required or initiated.</p></div><div className="product-preview"><p className="eyebrow">Inside a DigiLearn lesson</p><h2>A reader built for concentration</h2><LessonFigure title="Purpose, practice, evidence" description="Each lesson moves from a defined outcome through practical work to reviewable evidence." labels={["Purpose", "Practice", "Evidence"]} /><ul><li>Clear objectives and explanations</li><li>Worked examples and knowledge checks</li><li>Personal notes saved on this device</li></ul></div></section>
  <section className="home-strip" aria-label="Product facts"><div><strong>{COURSES.length}</strong><span>real catalogue entries</span></div><div><strong>{topics}</strong><span>topic areas</span></div><div><strong>8</strong><span>practice decks preserved</span></div><div><strong>Open</strong><span>current learning access</span></div></section>
  <section className="home-section"><div className="section-heading"><div><p className="eyebrow">Start with a course</p><h2>Explore practical subjects</h2></div><Link href="/courses">View the complete catalogue →</Link></div><div className="editorial-course-grid">{COURSES.slice(0, 6).map((course) => <CourseCard key={course.id} course={course} />)}</div></section>
  <section className="learning-method"><div><p className="eyebrow">How learning works</p><h2>Read, practise, record, continue.</h2><p>Course outlines keep context visible without crowding the reading column. Knowledge checks assess material taught in the lesson, while personal notes remain clearly separate from provided study material.</p></div><ol><li><strong>Choose</strong><span>Search by title, topic, skill or level.</span></li><li><strong>Study</strong><span>Work through structured, appropriately paced lessons.</span></li><li><strong>Check</strong><span>Answer a focused question and review the explanation.</span></li><li><strong>Return</strong><span>Continue from activity genuinely stored in this browser.</span></li></ol></section>
  <section className="local-first-banner"><h2>Local-first for this stage</h2><p>Notes, progress and the current profile stay in this browser. They do not synchronize or receive cloud backup. Clearing browser data can remove them.</p><Link href="/dashboard">View your learning dashboard →</Link></section></main><SiteFooter /></>;
}
