import type { Metadata } from "next";
import Link from "next/link";
import { COURSES } from "./courses/courses";
import { CourseCard } from "@/components/CourseCard";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { PATHWAYS } from "@/lib/course-editorial";
export const metadata: Metadata = { alternates: { canonical: "/" } };
export default function HomePage() { return <><SiteHeader/><main id="main-content">
<section className="editorial-hero problem-hero"><div><p className="eyebrow">Practical learning for real work</p><h1>Build digital skills you can use, show and improve.</h1><p>Work through guided projects, real examples, working code and practical documents designed around tasks people actually perform in jobs, freelance work and small businesses.</p><div className="hero-actions"><a className="button primary inline-button" href="#learning-goals">Choose your learning goal</a><Link className="text-link" href="/courses">Explore practical courses</Link></div></div><div className="product-preview lesson-proof"><div className="preview-toolbar"><span>sales-summary.py</span><span>Test passed</span></div><pre><code>{`total = sum(order["amount"] for order in orders)\nprint(f"Revenue: KES {total:,.0f}")`}</code></pre><div className="preview-output"><span>Expected output</span><strong>Revenue: KES 184,500</strong><small>12 valid orders · 2 rows reviewed</small></div><ul><li>Readable source code</li><li>Expected result and validation</li><li>Notes beside the lesson</li></ul></div></section>
<section id="learning-goals" className="home-section goal-section"><div className="section-heading"><div><p className="eyebrow">Start with the problem</p><h2>What do you need to achieve?</h2></div></div><div className="goal-grid">{PATHWAYS.map((p)=><Link key={p.id} href={`/courses?pathway=${p.id}`}><h3>{p.title}</h3><p>{p.problem}</p><span>{p.courseIds.length} matched courses</span></Link>)}</div></section>
<section className="home-strip proof-strip" aria-label="Learning evidence"><div><strong>Working code</strong><span>with expected output</span></div><div><strong>Practical files</strong><span>built from safe examples</span></div><div><strong>Knowledge checks</strong><span>linked to each lesson</span></div><div><strong>Local progress</strong><span>honestly stored on this device</span></div></section>
<section className="home-section"><div className="section-heading"><div><p className="eyebrow">High-value starting points</p><h2>Courses that lead to demonstrable work</h2></div><Link href="/courses">View the complete catalogue</Link></div><div className="editorial-course-grid">{["html-css","typescript","python-ai","security-fundamentals","chatgpt-mastery","financial-modelling"].map((id)=><CourseCard key={id} course={COURSES.find((c)=>c.id===id)!}/>)}</div></section>
<section className="learning-method"><div><p className="eyebrow">How DigiLearn teaches</p><h2>Understand the problem. Produce evidence. Review the result.</h2><p>Lessons combine explanation with worked examples, knowledge checks and practical tasks. Personal notes stay separate from provided study material.</p></div><ol><li><strong>Choose a goal</strong><span>Start from the capability you need, not a tool list.</span></li><li><strong>Study an example</strong><span>See real code, documents, data or decisions in context.</span></li><li><strong>Build the output</strong><span>Follow practical steps and compare against success criteria.</span></li><li><strong>Continue</strong><span>Return to progress genuinely stored in this browser.</span></li></ol></section>
<section className="local-first-banner"><p className="eyebrow">Open-access stage</p><h2>Learn every lesson without starting a payment.</h2><p>All courses are currently open. Future KES prices remain visible for transparency. Notes, progress and profiles stay in this browser; they do not synchronize or receive cloud backup, and clearing browser data can remove them.</p><Link href="/dashboard">View your learning dashboard</Link></section></main><SiteFooter/></>; }
