"use client";
import { useEffect, useMemo, useState } from "react";
import type { Course } from "@/app/courses/courses";
import { filterCourses } from "@/lib/course-search";
import { editorialFor, PATHWAYS } from "@/lib/course-editorial";
import { CourseCard } from "./CourseCard";
type Sort = "recommended"|"practical"|"beginner"|"shortest"|"advanced"|"reviewed";
export function CourseCatalogue({ courses }: { courses: Course[] }) {
 const [query,setQuery]=useState(""); const [topic,setTopic]=useState("all"); const [level,setLevel]=useState("all"); const [pathway,setPathway]=useState("all"); const [sort,setSort]=useState<Sort>("recommended"); const [filtersOpen,setFiltersOpen]=useState(false);
 useEffect(()=>{ const value=new URLSearchParams(window.location.search).get("pathway"); if(value&&PATHWAYS.some((p)=>p.id===value)) setPathway(value); },[]);
 const topics=useMemo(()=>[...new Set(courses.map((c)=>c.topic))].sort(),[courses]);
 const filtered=useMemo(()=>{ const path=PATHWAYS.find((p)=>p.id===pathway); const base=filterCourses(courses,{query,topic,level}).filter((c)=>!path||path.courseIds.includes(c.id)); return [...base].sort((a,b)=> sort==="shortest"?a.hours-b.hours:sort==="beginner"?(a.level==="Beginner"?-1:1):sort==="advanced"?(a.level==="Advanced"?-1:1):sort==="practical"?(editorialFor(b).pathways.length-editorialFor(a).pathways.length):a.title.localeCompare(b.title)); },[courses,query,topic,level,pathway,sort]);
 const count=[topic,level,pathway].filter((x)=>x!=="all").length; const reset=()=>{setQuery("");setTopic("all");setLevel("all");setPathway("all");};
 const controls=<><label><span>Learning pathway</span><select value={pathway} onChange={(e)=>setPathway(e.target.value)}><option value="all">All goals</option>{PATHWAYS.map((p)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label><span>Topic</span><select value={topic} onChange={(e)=>setTopic(e.target.value)}><option value="all">All topics</option>{topics.map((t)=><option key={t} value={t}>{t.replace("-"," ")}</option>)}</select></label><label><span>Level</span><select value={level} onChange={(e)=>setLevel(e.target.value)}><option value="all">All levels</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><button type="button" className="button quiet" onClick={reset}>Clear filters</button></>;
 return <><div className="catalogue-toolbar"><label className="search-field"><span>Search outcomes, projects, skills and tools</span><input type="search" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Try data analysis, portfolio or Python"/></label><button className="mobile-filter-button" type="button" aria-expanded={filtersOpen} aria-controls="catalogue-filter-panel" onClick={()=>setFiltersOpen(!filtersOpen)}>Filters{count?` (${count})`:""}</button><label className="sort-field"><span>Sort</span><select value={sort} onChange={(e)=>setSort(e.target.value as Sort)}><option value="recommended">Recommended</option><option value="practical">Most practical</option><option value="beginner">Beginner-friendly</option><option value="shortest">Shortest</option><option value="advanced">Advanced</option><option value="reviewed">Recently reviewed</option></select></label></div><form id="catalogue-filter-panel" className={`catalogue-filters ${filtersOpen?"open":""}`} onSubmit={(e)=>e.preventDefault()}><div className="mobile-filter-heading"><strong>Filter courses</strong><button type="button" onClick={()=>setFiltersOpen(false)}>Close</button></div>{controls}</form><div className="catalogue-result"><p aria-live="polite">{filtered.length} courses</p><span>Every result is currently open for learning.</span></div>{filtered.length?<div className="editorial-course-grid">{filtered.map((c)=><CourseCard key={c.id} course={c}/>)}</div>:<div className="empty-state"><h2>No courses match</h2><p>Try a broader goal, skill or level.</p><button className="button primary" onClick={reset}>Clear filters</button></div>}</>;
}
