import Link from "next/link";
import type { Course } from "@/app/courses/courses";
import type { CourseCurriculum } from "@/lib/learning-types";
import { editorialFor } from "@/lib/course-editorial";
import { AccessBadge } from "./CourseCard";
import { CourseCover } from "./CourseCover";
import { DOWNLOADS_BY_TOPIC } from "@/lib/course-assets";
import { SiteFooter, SiteHeader } from "./SiteChrome";
export function CourseOverview({course,curriculum}:{course:Course;curriculum:CourseCurriculum}) { const e=editorialFor(course); const first=curriculum.modules[0].lessons[0]; const download=DOWNLOADS_BY_TOPIC[course.topic]; return <><SiteHeader/><main id="main-content" className="course-overview"><header className="course-overview-hero"><div><p className="eyebrow">{course.level} · Reviewed {e.lastReviewed}</p><AccessBadge course={course}/><h1>{course.title}</h1><p className="course-overview-lead">{e.outcome}. You will finish with {e.project}.</p><div className="hero-actions"><Link className="button primary inline-button" href={`/courses/${course.id}?lesson=${first.id}`}>Start first lesson</Link><Link className="text-link" href={`/courses/${course.id}/guide`}>Open printable guide</Link></div><p className="browser-limit">Progress and notes are stored only in this browser. They are not synchronized or backed up.</p></div><CourseCover course={course} priority/></header><div className="course-decision-grid"><section><p className="eyebrow">The problem</p><h2>What this course helps you do</h2><p>{curriculum.overview}</p><h3>Who it is for</h3><p>{curriculum.intendedLearner}</p><h3>Prerequisites</h3><ul>{curriculum.prerequisites.map((x)=><li key={x}>{x}</li>)}</ul></section><aside><h2>Course at a glance</h2><dl><div><dt>Time</dt><dd>{Math.round(curriculum.durationMinutes/60)} hours</dd></div><div><dt>Level</dt><dd>{course.level}</dd></div><div><dt>Lessons</dt><dd>{curriculum.modules.reduce((n,m)=>n+m.lessons.length,0)}</dd></div><div><dt>Tools</dt><dd>{curriculum.practicalOutcome.tools.join(", ")}</dd></div></dl></aside></div><section className="course-project-showcase"><p className="eyebrow">Portfolio-ready project</p><h2>{curriculum.practicalOutcome.objective}</h2><p><strong>Deliverable:</strong> {curriculum.practicalOutcome.expectedOutput}</p><div><a href={download.path} download>{download.label}</a><a href="/downloads/digilearn-project-brief.md" download>Project brief</a></div><p className="download-description">{download.description} All data is fictional and safe for practice.</p></section><section className="course-modules"><p className="eyebrow">Course plan</p><h2>From first concept to finished work</h2>{curriculum.modules.map((m,i)=><article key={m.id}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{m.title}</h3><p>{m.summary}</p><ol>{m.lessons.map((l)=><li key={l.id}><Link href={`/courses/${course.id}?lesson=${l.id}`}>{l.title}<small>{l.minutes} min</small></Link></li>)}</ol></div></article>)}</section><section className="course-sources"><h2>Authoritative references</h2><ul>{curriculum.references.map((s)=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><span>{s.organization}</span></li>)}</ul></section></main><SiteFooter/></>; }
