"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Course } from "@/app/courses/courses";
import { filterCourses } from "@/lib/course-search";
import { editorialFor, PATHWAYS } from "@/lib/course-editorial";
import { reviewFor } from "@/lib/course-governance";
import { CourseCard } from "./CourseCard";
import { useModalSheet } from "@/lib/use-modal-sheet";
type Sort = "recommended"|"practical"|"beginner"|"shortest"|"advanced"|"reviewed";
export function CourseCatalogue({ courses }: { courses: Course[] }) {
 const [query,setQuery]=useState(""); const [topic,setTopic]=useState("all"); const [level,setLevel]=useState("all"); const [pathway,setPathway]=useState("all"); const [sort,setSort]=useState<Sort>("recommended"); const [filtersOpen,setFiltersOpen]=useState(false);
 const filterRef=useRef<HTMLFormElement>(null); const filterButtonRef=useRef<HTMLButtonElement>(null); const closeFilters=useCallback(()=>setFiltersOpen(false),[]); useModalSheet(filtersOpen,filterRef,filterButtonRef,closeFilters);
 useEffect(()=>{ const value=new URLSearchParams(window.location.search).get("pathway"); if(value&&PATHWAYS.some((p)=>p.id===value)) setPathway(value); },[]);
 const topics=useMemo(()=>[...new Set(courses.map((c)=>c.topic))].sort(),[courses]);
 const filtered=useMemo(()=>{ const path=PATHWAYS.find((p)=>p.id===pathway); const base=filterCourses(courses,{query,topic,level}).filter((c)=>!path||path.courseIds.includes(c.id)); const levelRank=(course:Course,preferred:Course["level"])=>course.level===preferred?0:course.level==="Intermediate"?1:2; return [...base].sort((a,b)=>{ if(sort==="shortest") return a.hours-b.hours||a.title.localeCompare(b.title); if(sort==="beginner") return levelRank(a,"Beginner")-levelRank(b,"Beginner")||a.title.localeCompare(b.title); if(sort==="advanced") return levelRank(a,"Advanced")-levelRank(b,"Advanced")||a.title.localeCompare(b.title); if(sort==="practical") return editorialFor(b).pathways.length-editorialFor(a).pathways.length||a.title.localeCompare(b.title); if(sort==="reviewed") return (reviewFor(b).reviewedAt??"").localeCompare(reviewFor(a).reviewedAt??"")||a.title.localeCompare(b.title); return courses.indexOf(a)-courses.indexOf(b); }); },[courses,query,topic,level,pathway,sort]);
 const count=[topic,level,pathway].filter((x)=>x!=="all").length; const reset=()=>{setQuery("");setTopic("all");setLevel("all");setPathway("all");};
 const controls=<><label><span>Learning pathway</span><select value={pathway} onChange={(e)=>setPathway(e.target.value)}><option value="all">All goals</option>{PATHWAYS.map((p)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label><span>Topic</span><select value={topic} onChange={(e)=>setTopic(e.target.value)}><option value="all">All topics</option>{topics.map((t)=><option key={t} value={t}>{t.replace("-"," ")}</option>)}</select></label><label><span>Level</span><select value={level} onChange={(e)=>setLevel(e.target.value)}><option value="all">All levels</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><button type="button" className="button quiet" onClick={reset} disabled={!query&&!count}>Clear all</button></>;
 return <><div className="catalogue-toolbar"><label className="search-field"><span>Search outcomes, projects, skills and tools</span><span className="search-control"><input type="search" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Try data analysis, portfolio or Python"/>{query?<button type="button" onClick={()=>setQuery("")} aria-label="Clear search">Clear</button>:null}</span></label><button ref={filterButtonRef} className="mobile-filter-button" type="button" aria-expanded={filtersOpen} aria-controls="catalogue-filter-panel" onClick={()=>setFiltersOpen(!filtersOpen)}>Filters{count?` (${count})`:""}</button><label className="sort-field"><span>Sort courses</span><select value={sort} onChange={(e)=>setSort(e.target.value as Sort)}><option value="recommended">Recommended order</option><option value="practical">Most pathway matches</option><option value="beginner">Beginner first</option><option value="shortest">Shortest first</option><option value="advanced">Advanced first</option><option value="reviewed">Recently reviewed</option></select></label></div><form ref={filterRef} id="catalogue-filter-panel" role={filtersOpen?"dialog":undefined} aria-modal={filtersOpen?"true":undefined} aria-labelledby={filtersOpen?"filter-sheet-title":undefined} className={`catalogue-filters ${filtersOpen?"open":""}`} onSubmit={(e)=>e.preventDefault()}><div className="mobile-filter-heading"><strong id="filter-sheet-title">Filter courses</strong><button type="button" onClick={closeFilters}>Close</button></div>{controls}</form><div className="catalogue-result"><p aria-live="polite"><strong>{filtered.length}</strong> {filtered.length===1?"course":"courses"} found</p><span>All results are currently open—no payment required.</span></div>{filtered.length?<div className="editorial-course-grid">{filtered.map((c)=><CourseCard key={c.id} course={c}/>)}</div>:<div className="empty-state"><h2>No courses match these filters</h2><p>Clear a filter or try a broader skill, tool, or outcome.</p><button className="button primary" onClick={reset}>Show all courses</button></div>}</>;
}
