import type { Course } from "@/app/courses/courses";
export type Pathway = { id: string; title: string; problem: string; courseIds: string[] };
export const PATHWAYS: Pathway[] = [
  { id:"job-ready", title:"Get job-ready", problem:"Practise the digital tasks expected in entry-level work.", courseIds:["html-css","javascript","python-fund","sql","ai-productivity"] },
  { id:"digital-service", title:"Start a digital service", problem:"Develop a service and evidence you can show a client.", courseIds:["freelance-dev","webflow","content-creator","digital-biz"] },
  { id:"build-web", title:"Build websites and applications", problem:"Move from a brief to a responsive, tested product.", courseIds:["html-css","javascript","typescript","react-nextjs","node-api"] },
  { id:"ai-at-work", title:"Use AI at work", problem:"Use AI with verification, privacy checks and human judgement.", courseIds:["chatgpt-mastery","ai-productivity","responsible-ai","prompt-engineering"] },
  { id:"analyse-data", title:"Analyse data and make decisions", problem:"Clean evidence, ask useful questions and communicate findings.", courseIds:["python-ai","sql","data-viz","open-data-analysis"] },
  { id:"grow-business", title:"Grow a small business", problem:"Create clearer operations, campaigns and financial records.", courseIds:["digital-biz","zapier","financial-modelling","ecommerce-ai"] },
  { id:"productivity", title:"Master workplace productivity", problem:"Build repeatable systems for documents, data and teamwork.", courseIds:["ai-productivity","notion-system","airtable","make-automation"] },
  { id:"safer-habits", title:"Build safer digital habits", problem:"Protect accounts, devices, networks and sensitive information.", courseIds:["security-fundamentals","privacy-tools","network-security","data-privacy-ethics"] },
  { id:"communication", title:"Improve professional communication", problem:"Turn research and ideas into clear, credible work.", courseIds:["ai-writing","data-journalism","content-creator","freelance-dev"] },
  { id:"portfolio", title:"Create a credible portfolio", problem:"Finish reviewable work that demonstrates how you solve problems.", courseIds:["html-css","typescript","data-viz","freelance-dev"] },
];
const TOPIC: Record<string,[string,string,string]> = { "ai-tools":["Build a responsible AI workflow for a real work task","a documented prompt, verification and revision workflow","workflow"], webdev:["Build and test a responsive digital product","a responsive, accessible application you can demonstrate","software"], data:["Turn untidy data into a defensible finding","a cleaned dataset, analysis and decision-ready chart","data"], automation:["Design a reliable workflow that reduces repetitive work","a mapped automation with tests and recovery steps","workflow"], security:["Apply practical protection to accounts and systems","a prioritised security review and action plan","security"], business:["Develop a service or business process you can explain clearly","a client-ready brief, plan and evidence pack","document"], databases:["Model, query and explain dependable data","a working data model with validated queries","data"], ethics:["Evaluate technology decisions with evidence and accountability","a documented risk and impact assessment","document"], finance:["Build a clearer, auditable financial workflow","a fictional financial model with assumptions and checks","data"], healthcare:["Work with digital-health information responsibly","a safe, fictional health-data workflow and review","health"], policy:["Use evidence to explain a public-interest problem","an evidence brief with a reproducible analysis","document"] };
export function editorialFor(course: Course) { const [outcome,project,family]=TOPIC[course.topic]??TOPIC.business; return { outcome,project,family,pathways:PATHWAYS.filter((p)=>p.courseIds.includes(course.id)),editorialStatus:"Structured draft",version:"0.9" }; }
