import type { Course } from "@/app/courses/courses";

export type CourseIconKey = "airtable"|"anthropic"|"bitcoin"|"claude"|"css"|"d3"|"elevenlabs"|"ethereum"|"expo"|"fitbit"|"githubcopilot"|"googlebigquery"|"googlecloud"|"googlegemini"|"html5"|"javascript"|"kali"|"langchain"|"make"|"mongodb"|"n8n"|"nextjs"|"nodejs"|"notion"|"openai"|"pandas"|"perplexity"|"plotly"|"postgresql"|"python"|"pytorch"|"react"|"redis"|"scikitlearn"|"shopify"|"snowflake"|"solidity"|"stripe"|"suno"|"supabase"|"tailwind"|"tensorflow"|"tor"|"typescript"|"webflow"|"zapier";
export type CourseCoverAsset = { assetId:string; courseId:string; iconKeys:CourseIconKey[]; alt:string; caption:string; sourceReview:"cc0-brand-icons"; topicLabel:string; tone:string };

const ICONS_BY_COURSE: Partial<Record<string,CourseIconKey[]>> = {
  "chatgpt-mastery":["openai"],"claude-mastery":["claude","anthropic"],"prompt-engineering":["openai","claude"],midjourney:["openai"],"copilot-dev":["githubcopilot"],"perplexity-gemini":["perplexity","googlegemini"],"ai-writing":["openai"],"sora-video":["openai"],"ai-productivity":["notion","openai"],"llm-agents":["langchain","openai"],"ai-audio":["suno","elevenlabs"],
  "html-css":["html5","css"],javascript:["javascript"],"react-nextjs":["react","nextjs"],typescript:["typescript"],tailwind:["tailwind"],"node-api":["nodejs"],fullstack:["nextjs","supabase"],"react-native":["react","expo"],
  "python-fund":["python"],"python-ai":["python","pandas"],"machine-learning":["scikitlearn","python"],"deep-learning":["pytorch","tensorflow"],nlp:["pytorch","python"],sql:["postgresql"],"data-viz":["plotly","python"],
  "make-automation":["make"],n8n:["n8n"],zapier:["zapier"],airtable:["airtable"],"notion-system":["notion"],webflow:["webflow"],"ethical-hacking":["kali"],"privacy-tools":["tor"],"cloud-security":["googlecloud"],
  "saas-launch":["stripe","nextjs"],"content-creator":["openai"],"ecommerce-ai":["shopify","openai"],"sql-fundamentals":["postgresql"],"postgresql-advanced":["postgresql"],"nosql-mongodb":["mongodb","redis"],"database-design":["postgresql"],"vector-databases":["postgresql","langchain"],"data-warehousing":["googlebigquery","snowflake"],"sql-for-finance":["postgresql"],
  "python-finance":["python","pandas"],"blockchain-web3":["ethereum","solidity"],"ai-trading":["python","tensorflow"],"financial-modelling":["python","pandas"],"crypto-fundamentals":["bitcoin","ethereum"],"biomedical-data":["python","pandas"],"wearables-iot-health":["fitbit"],"open-data-analysis":["python","pandas"],"data-journalism":["d3"],"climate-data-tech":["python","pandas"]
};
const TOPIC_DEFAULTS:Record<string,CourseIconKey[]>={"ai-tools":["openai"],webdev:["html5","css"],data:["python","pandas"],automation:["zapier"],security:["kali"],business:["stripe"],databases:["postgresql"],ethics:["openai"],finance:["python"],healthcare:["python"],policy:["d3"]};
const TOPIC_LABELS:Record<string,string>={"ai-tools":"AI tools",webdev:"Web development",data:"Data & Python",automation:"Automation",security:"Cybersecurity",business:"Digital business",databases:"Databases",ethics:"Responsible AI",finance:"Finance & fintech",healthcare:"Digital health",policy:"Policy & civic tech"};
const TOPIC_TONES:Record<string,string>={"ai-tools":"violet",webdev:"blue",data:"gold",automation:"coral",security:"indigo",business:"emerald",databases:"cyan",ethics:"plum",finance:"green",healthcare:"teal",policy:"slate"};
export function coverAssetFor(course:Course):CourseCoverAsset { const iconKeys=ICONS_BY_COURSE[course.id]??TOPIC_DEFAULTS[course.topic]??["openai"]; return {assetId:`cover-${course.id}-2026-08-brand-stack`,courseId:course.id,iconKeys,alt:`${course.title} course cover featuring recognizable ${iconKeys.join(" and ")} technology marks.`,caption:`Technology marks for ${course.title}, sourced from the CC0-licensed Simple Icons project.`,sourceReview:"cc0-brand-icons",topicLabel:TOPIC_LABELS[course.topic]??"Digital skills",tone:TOPIC_TONES[course.topic]??"blue"}; }

export const DOWNLOADS_BY_TOPIC:Record<string,{path:string;label:string;description:string}>={
  "ai-tools":{path:"/downloads/responsible-ai-workflow.md",label:"Responsible AI workflow",description:"A source, instruction, review and privacy-check worksheet."},webdev:{path:"/downloads/responsive-interface-starter.html",label:"Responsive interface starter",description:"A semantic HTML starter with a clear project region."},data:{path:"/downloads/analysis-practice-data.csv",label:"Analysis practice dataset",description:"Fictional monthly service data with units and dates."},automation:{path:"/downloads/automation-test-plan.md",label:"Automation test plan",description:"A trigger, validation, recovery and audit worksheet."},security:{path:"/downloads/security-review-sheet.csv",label:"Security review sheet",description:"An account and device control review with evidence fields."},business:{path:"/downloads/client-proposal-template.md",label:"Client proposal template",description:"A fictional service proposal with scope, timeline and acceptance checks."},databases:{path:"/downloads/relational-data-practice.sql",label:"Relational data practice",description:"Safe SQL schema and queries for a fictional service business."},ethics:{path:"/downloads/technology-impact-review.md",label:"Technology impact review",description:"A risk, affected-party, evidence and mitigation worksheet."},finance:{path:"/downloads/cash-flow-practice.csv",label:"Cash-flow practice file",description:"Fictional receipts and expenses with dates and KES amounts."},healthcare:{path:"/downloads/health-data-review.json",label:"Health-data review sample",description:"De-identified fictional records for validation practice."},policy:{path:"/downloads/evidence-brief-template.md",label:"Evidence brief template",description:"A source-led public-interest analysis structure."}
};

export function courseGuidePdfPath(courseId:string){return `/downloads/course-guides/${courseId}-study-guide.pdf`;}
