export type VideoResource = { title: string; provider: string; url: string; purpose: string; task: string; reviewed: string };
const video = (title: string, provider: string, url: string, purpose: string, task: string): VideoResource => ({ title, provider, url, purpose, task, reviewed: "2026-10-07" });
export function videosForCourse(id: string): VideoResource[] {
  if (id === "postgresql-advanced" || id === "sql-fundamentals") id = "sql";
  if (id === "html-css") return [video("Intro to HTML/CSS: making webpages", "Khan Academy", "https://www.khanacademy.org/computing/html-css", "Follow short explanations alongside editable examples of HTML elements and CSS rules.", "Pause after an example. Recreate it in your own file, then change one rule and explain the result.")];
  if (id === "python-fund" || id === "python-ai") return [video("CS50: programming with Python", "Harvard OpenCourseWare", "https://cs50.harvard.edu/python/", "Choose the lecture on functions, loops, exceptions, tests or files that matches your current task.", "Before running an example, predict its output. Try an empty input and record how the program behaves.")];
  if (id === "sql" || id === "postgresql") return [video("CS50: databases with SQL", "Harvard OpenCourseWare", "https://cs50.harvard.edu/sql/", "Watch Querying or Relating to see selection and joins explained using actual tables. Examples begin with SQLite; check syntax when using PostgreSQL.", "Draw two small tables, predict the joined rows, then compare your prediction with the query result.")];
  if (id === "machine-learning" || id === "deep-learning") return [video("But what is a neural network?", "3Blue1Brown · Grant Sanderson", "https://www.3blue1brown.com/lessons/neural-networks/", "Use the animated explanation to connect inputs, weights, activations and outputs. This is a conceptual supplement, not a framework tutorial.", "Sketch a tiny network with two inputs and one output. Label each weight and explain what training changes.")];
  return [];
}
export type Troubleshooting = { symptom: string; inspect: string; action: string; proof: string };
export const TROUBLESHOOTING: Record<string, Troubleshooting> = {
  webdev: { symptom: "The page works on a laptop but spills sideways on a phone.", inspect: "At a narrow viewport, inspect fixed widths, long unbroken text, images and grid children. Identify the first element wider than its parent.", action: "Replace unnecessary fixed widths with max-width: 100%; allow grid children to shrink with min-width: 0. Keep wide code and tables in their own scroll containers.", proof: "At 320, 390, 768 and 1440 CSS pixels, the page itself has no horizontal overflow. Keyboard focus and controls stay visible at 200% zoom." },
  data: { symptom: "A chart or total changes unexpectedly after cleaning the data.", inspect: "Compare row counts, missing values, duplicate identifiers and column types before and after each transformation. Check whether dates and decimal values were parsed correctly.", action: "Keep the raw file unchanged. Apply one named cleaning rule at a time and save the count of affected rows. Do not silently replace missing values with zero.", proof: "Hand-calculate a five-row sample. Its total agrees with the script, and every removed or changed record has an explained rule." },
  databases: { symptom: "A join returns more rows than expected.", inspect: "Count matching records for each join key in both tables. A key repeated on both sides creates multiple combinations.", action: "Decide the intended row grain first: one row per customer, order or item. Aggregate at that grain or correct the join condition; do not hide the problem with DISTINCT.", proof: "Use two customers and three orders as a fixture. Predict every result row and check unmatched records separately." },
  automation: { symptom: "One incoming event creates two records or sends two messages.", inspect: "Look for retries, repeated webhook delivery and overlapping schedules. Compare event identifiers and execution logs rather than only timestamps.", action: "Store a stable event identifier and make repeated handling return the existing result. Use a unique constraint or atomic operation when simultaneous runs are possible.", proof: "Send the same test event twice, then simultaneously. Only one intended side effect occurs, and the other executions report that it was already handled." },
  "ai-tools": { symptom: "An answer sounds convincing but includes a claim you cannot verify.", inspect: "Separate supplied evidence from generated assertions. Open the original source and check the date, scope and exact support for each consequential claim.", action: "Remove unsupported claims or label them as uncertain. Ask for a source-grounded revision with explicit gaps, then verify the revision yourself.", proof: "Another reader can follow each important claim to a real source or a reproducible calculation. A fluent answer alone does not pass." },
  security: { symptom: "An account behaves unexpectedly or a sign-in alert appears.", inspect: "Use the service's official application or a known address to inspect sessions and recovery settings. Preserve timestamps and relevant evidence.", action: "Follow the provider's account recovery steps, revoke unfamiliar sessions and review multifactor authentication. Escalate workplace incidents through the organisation's response process.", proof: "Recovery access is under the owner's control, unfamiliar sessions are revoked, and the incident and follow-up actions are recorded." },
  business: { symptom: "People express interest but do not buy or complete the next step.", inspect: "Distinguish praise from behaviour. Check whether the offer states the audience, deliverable, price, timing and next action clearly.", action: "Interview a small number of intended customers about their last attempt to solve the problem. Test one specific offer and record actual responses without inventing testimonials.", proof: "Report how many people saw the offer, how many acted and what objections they raised. Keep the sample size visible." },
  ethics: { symptom: "An average performance score hides worse results for some people.", inspect: "Compare relevant groups where collection and analysis are appropriate. Check sample sizes, missingness, error types and how the system will be used.", action: "Document who may be harmed and the available alternatives. Define an owner, a mitigation and a route for affected people to challenge a decision.", proof: "The review includes group-level limitations and an actionable response; a single overall score is not treated as evidence of fairness." },
  finance: { symptom: "A spreadsheet balance does not agree with the underlying records.", inspect: "Check the reporting period, currency, signs, duplicated entries and whether transfers were counted as income. Use fictional data for practice.", action: "Reconcile each transaction to a source record and list unresolved differences separately. Keep assumptions in named cells and avoid unexplained balancing entries.", proof: "Opening balance plus inflows minus outflows equals closing balance. Changing an assumption updates the model consistently." },
  healthcare: { symptom: "Two systems interpret the same health-data field differently.", inspect: "Compare the field's meaning, unit, coding system, timestamp and handling of missing values. Use synthetic records rather than patient data.", action: "Write a mapping with explicit transformations and reject ambiguous values for qualified review. Test both valid and invalid synthetic examples.", proof: "A reviewer can trace each output field to its source and mapping rule. Unresolved clinical meaning is not guessed." },
  policy: { symptom: "Two credible sources give different figures for the same issue.", inspect: "Compare dates, populations, definitions, units and collection methods. Look for revisions and differences in geographic coverage.", action: "State the difference explicitly and choose the source that fits the question. Present alternatives where the evidence cannot resolve the discrepancy.", proof: "The brief identifies its population, period, source and limitations, so readers can understand and reproduce the comparison." },
};
