import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { COURSE_PRICE_KES, formatKES } from "@/lib/pricing";

export const metadata: Metadata = { title: "Learning access", description: "Review DigiLearn open-preview access and honest future-price information.", alternates: { canonical: "/pricing" } };

export default function PricingPage() {
  return <><SiteHeader /><main id="main-content" className="access-page"><header className="editorial-hero compact"><p className="eyebrow">Learning access</p><h1>Every course is currently open.</h1><p>Payments are not required during this open-learning period. Opening a course does not initiate a payment or create a purchase record.</p></header><section className="access-policy-card"><div><p className="eyebrow">Current policy</p><h2>Free learning access</h2><p>Read every available lesson, complete lesson checks and final assessments, save device-local notes, print study material, and use the practice decks.</p></div><dl><div><dt>Current charge</dt><dd>KES 0</dd></div><div><dt>Future reference price</dt><dd>{formatKES(COURSE_PRICE_KES)} per course</dd></div><div><dt>Payment required now</dt><dd>No</dd></div><div><dt>Payment provider</dt><dd>Not active</dd></div></dl></section><section className="home-section narrow"><h2>About the future reference price</h2><p>Some course cards show <strong>Future price: {formatKES(COURSE_PRICE_KES)}</strong> for planning transparency. It is not a charge, checkout offer, or promise of the final launch price. Paid access will begin only after pricing, currency rules, customer support, refunds, and secure payment verification are ready.</p><h2>What is stored locally</h2><p>Learning progress, assessment attempts, personal notes, practice history, and the optional browser-local profile remain on this device. DigiLearn does not currently provide cloud synchronization, account recovery, certificates, or instructor review.</p></section></main><SiteFooter /></>;
}
