import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

export const metadata: Metadata = { title: "Learning access", description: "Review DigiLearn open-preview access and payment-readiness boundaries.", alternates: { canonical: "/pricing" } };

export default function PricingPage() {
  return <><SiteHeader /><main id="main-content" className="access-page"><header className="editorial-hero compact"><p className="eyebrow">Learning access</p><h1>Every course is currently open.</h1><p>Payments are not required during this open-learning period. Opening a course does not initiate a payment or create a purchase record.</p><div className="hero-actions"><Link className="button primary inline-button" href="/courses">Browse open courses</Link><Link className="text-link" href="/dashboard">Review local progress</Link></div></header><section className="access-policy-card"><div><p className="eyebrow">Current policy</p><h2>Open learning access</h2><p>Read every available lesson, complete formative knowledge checks, save device-local notes, print study material, and use the practice decks.</p></div><dl><div><dt>Current charge</dt><dd>KES 0</dd></div><div><dt>Future price</dt><dd>Not approved</dd></div><div><dt>Payment required now</dt><dd>No</dd></div><div><dt>Payment provider</dt><dd>Not active</dd></div></dl></section><section className="home-section narrow access-details"><article><p className="eyebrow">Pricing clarity</p><h2>Why no future price is displayed</h2><p>A responsible price requires an approved product definition, currency and tax policy, refund terms, customer support, durable entitlements and verified course quality. DigiLearn will not present a launch price before those decisions are complete.</p></article><article><p className="eyebrow">Device privacy</p><h2>What is stored locally</h2><p>Learning progress, knowledge-check attempts, personal notes, practice history, and the optional device profile remain on this device. DigiLearn does not currently provide cloud synchronization, account recovery, certificates, or instructor review.</p></article></section><section className="access-next-step"><div><p className="eyebrow">Ready to begin?</p><h2>Choose a practical outcome and start learning.</h2><p>You can open any course immediately and return to saved progress on this device.</p></div><Link className="button primary inline-button" href="/courses">Explore the catalogue</Link></section></main><SiteFooter /></>;
}
