import type { FoundationSpec } from "./foundation-spec";
import { sqlSource as source } from "./foundation-spec";

const sales = "WITH sales(id, customer, amount, status) AS (\n  VALUES (1, 'Amina', 120, 'paid'),\n         (2, 'Amina', 80, 'pending'),\n         (3, 'Brian', 50, 'paid'),\n         (4, 'Chen', NULL, 'paid')\n)\n";
export const SQL_LESSONS: Record<number, FoundationSpec> = {
  0: {
    title: "Select columns and control row order", intro: "Read a small fictional sales table without changing any stored data. Choose explicit output columns and a stable ordering so the result is easy to understand and does not depend on the database's incidental execution order.",
    explanation: "SELECT names the output columns; FROM supplies the records. ORDER BY defines the result order. A WITH fixture keeps the example self-contained and read-only; it exists only for this statement.", code: sales + "SELECT id, customer, amount\nFROM sales\nORDER BY id;", output: "id | customer | amount\n1  | Amina    | 120\n2  | Amina    | 80\n3  | Brian    | 50\n4  | Chen     | NULL",
    terms: ["Columns", "Rows", "Order"], objectives: ["Select explicit columns.", "Identify what each result row represents.", "Use ORDER BY for a predictable result."], nodes: ["Choose the fields needed for the question, rather than every available field.", "Each returned row represents one sales record in this fixture.", "Sort by the unique identifier to obtain a deterministic sequence."], steps: ["Run the complete statement, including the WITH fixture.", "Select only customer and status and count the returned rows.", "Order by amount descending and check the database's handling of NULL; do not infer a universal NULL order."], activity: "Write a query returning the four identifiers and their status. Keep one row per sale and order by the unique identifier.",
    mistakes: ["Assuming records have a reliable order without ORDER BY.", "Selecting every column when the report needs only a few.", "Confusing one sale with one unique customer."], summary: ["Explicit columns make a report's meaning visible.", "One row's meaning is its grain.", "ORDER BY controls the order of the displayed result."], check: { prompt: "What establishes a predictable order for this result?", options: ["The order rows were inserted", "An explicit ORDER BY on a suitable key", "Using SELECT *", "The customer's spelling"], answer: 1, explanation: "Result ordering needs ORDER BY. A unique sort key resolves ties and makes the sequence deterministic." }, source: source("Querying a table", "tutorial-select"),
  },
  1: {
    title: "Filter records with explicit conditions", intro: "A payment report should include only paid sales of at least 100 units. Translate that request into two conditions, combine them deliberately, and test records that match one condition while failing the other.", explanation: "WHERE filters individual input rows. AND requires both conditions to be true. Parentheses matter when mixing AND and OR; write them to show your intended grouping rather than relying on the reader to remember precedence.",
    code: sales + "SELECT id, customer, amount\nFROM sales\nWHERE status = 'paid' AND amount >= 100\nORDER BY id;", output: "id | customer | amount\n1  | Amina    | 120",
    terms: ["Predicate", "Combination", "Selection"], objectives: ["Translate a request into row conditions.", "Distinguish AND from OR.", "Test a threshold and non-matching status."], nodes: ["Each record is tested against the paid-status predicate.", "AND also requires the amount to meet the minimum.", "Only sale 1 satisfies both checks in this fixture."], steps: ["Change the minimum to 50 and predict the additional row.", "Replace AND with OR and explain each included record.", "Add a paid sale of exactly 100 and verify that >= includes it."], activity: "Select pending sales below 100, then paid sales below 100. Explain which record changes when the status condition changes.", mistakes: ["Using OR when every condition must hold.", "Omitting parentheses from a mixed logical expression.", "Forgetting to test a value exactly at the threshold."], summary: ["WHERE decides which input rows participate.", "AND and OR express different selection rules.", "Boundary records reveal threshold mistakes."], check: { prompt: "Which condition requires a sale to be both paid and at least 100?", options: ["status = 'paid' OR amount >= 100", "amount >= 100 alone", "status = 'paid' AND amount >= 100", "status <> 'paid' AND amount >= 100"], answer: 2, explanation: "AND requires both predicates. OR also admits records satisfying just one of them." }, source: source("Value expressions and logical conditions", "sql-expressions"),
  },
  2: {
    title: "Treat missing amounts as unknown", intro: "A missing sale amount is different from an amount of zero. Identify NULL explicitly and report what is missing before choosing any default, so an incomplete record does not silently become a confirmed zero-value transaction.", explanation: "Use IS NULL to detect missing values. Comparing a value to NULL with = does not produce true. COALESCE can provide a default, but the default must follow an explicit reporting rule rather than hiding missing data.",
    code: sales + "SELECT id, customer\nFROM sales\nWHERE amount IS NULL\nORDER BY id;", output: "id | customer\n4  | Chen",
    terms: ["NULL", "Inspection", "Policy"], objectives: ["Find a missing value with IS NULL.", "Distinguish zero from unknown.", "Explain when a default is justified."], nodes: ["Sale 4 has no recorded amount, represented by NULL.", "IS NULL identifies that missing-value state explicitly.", "The report flags the record for follow-up instead of inventing its amount."], steps: ["Replace IS NULL with = NULL and inspect the empty result.", "Add a sale with amount 0 and confirm it is not selected by IS NULL.", "Select COALESCE(amount, 0) alongside amount and explain what meaning the substituted zero does and does not establish."], activity: "Create a completeness report with sale identifier, original amount and a missing-amount flag. Include one zero amount and one NULL amount.", mistakes: ["Using = NULL to find missing values.", "Replacing unknown values with zero without a documented rule.", "Assuming NULL is an empty string."], summary: ["NULL marks missing or unknown information.", "IS NULL tests that state explicitly.", "A replacement value is a reporting choice, not recovered evidence."], check: { prompt: "Which predicate finds the fixture's missing amount?", options: ["amount = 0", "amount = NULL", "amount = ''", "amount IS NULL"], answer: 3, explanation: "IS NULL detects the missing-value marker. Zero, empty text and NULL have different meanings." }, source: source("Comparison predicates", "functions-comparison"),
  },
  3: {
    title: "Count records and summarise known amounts", intro: "The fixture has four records but only three recorded amounts. Compare COUNT(*), COUNT(amount) and SUM(amount) to produce a total that keeps its coverage visible instead of suggesting that every sale has a known value.", explanation: "COUNT(*) counts rows, while COUNT(amount) counts non-NULL amounts. SUM and AVG operate on known input values. Use both coverage and total when missing data can change the interpretation of a report.",
    code: sales + "SELECT COUNT(*) AS records,\n       COUNT(amount) AS known_amounts,\n       SUM(amount) AS known_total\nFROM sales;", output: "records | known_amounts | known_total\n4       | 3             | 250",
    terms: ["Population", "Coverage", "Aggregate"], objectives: ["Distinguish row and value counts.", "Compute a known-value total.", "Report coverage beside an aggregate."], nodes: ["Four records make up the input population.", "Only three records contain a known amount.", "The sum of those known amounts is 250; the missing amount remains unresolved."], steps: ["Calculate 120 + 80 + 50 by hand and compare the sum.", "Replace every amount with NULL and inspect COUNT(amount) and SUM(amount).", "Filter to an empty population and compare COUNT(*) with SUM(amount)."], activity: "Summarise only paid records and report their row count, known-value count and total. Explain why a paid record with a missing amount affects coverage.", mistakes: ["Calling a known-value total the complete revenue without checking missingness.", "Assuming COUNT(amount) counts every row.", "Expecting SUM of an empty input to be zero automatically."], summary: ["Counts and sums answer different questions.", "Aggregates over values exclude NULL inputs.", "A total needs a visible population and coverage."], check: { prompt: "Why do COUNT(*) and COUNT(amount) differ here?", options: ["One row has a NULL amount", "COUNT(*) ignores pending records", "COUNT(amount) removes duplicate customers", "SUM sorts the table"], answer: 0, explanation: "COUNT(*) counts all four rows. COUNT(amount) excludes the one NULL amount, so it returns three." }, source: source("Aggregate functions", "functions-aggregate"),
  },
  // Position 4 retains the detailed customer LEFT JOIN lesson.
  5: {
    title: "Separate row filters from group filters", intro: "Find customers whose known paid amounts total at least 100. Filter paid rows before grouping, then apply the threshold to each customer's aggregate, so a pending order cannot inflate a paid-sales result.", explanation: "WHERE filters input rows before aggregation. GROUP BY forms customer groups. HAVING filters those groups after the total is calculated. These clauses cannot be interchanged without changing the question.", code: sales + "SELECT customer, SUM(amount) AS paid_total\nFROM sales\nWHERE status = 'paid'\nGROUP BY customer\nHAVING SUM(amount) >= 100\nORDER BY customer;", output: "customer | paid_total\nAmina    | 120",
    terms: ["WHERE", "GROUP BY", "HAVING"], objectives: ["Filter records before grouping.", "Compute one result per customer.", "Filter groups using an aggregate."], nodes: ["WHERE removes Amina's pending sale before any totals are formed.", "GROUP BY combines each customer's remaining paid records.", "HAVING retains only groups whose known paid total meets the threshold."], steps: ["Remove WHERE and explain why Amina's total becomes 200.", "Change the threshold to 50 and predict the included customers.", "Add a second paid sale for Brian and check how grouping changes the result."], activity: "Return customers with at least two paid orders using COUNT(*) in HAVING. State how a missing amount affects an order count compared with an amount total.", mistakes: ["Including pending rows in a paid-total report.", "Trying to use a group aggregate as a row-level WHERE condition.", "Grouping by a display name when distinct customers can share it in real data."], summary: ["WHERE filters records before aggregation.", "GROUP BY defines the result grain.", "HAVING applies conditions to computed groups."], check: { prompt: "Where does a condition on SUM(amount) belong in this grouped query?", options: ["Only in ORDER BY", "In HAVING", "In the column name", "Inside the customer value"], answer: 1, explanation: "HAVING filters groups using their aggregate results. A row-level WHERE filter occurs before those groups are calculated." }, source: source("Aggregate functions in grouped queries", "tutorial-agg"),
  },
  6: {
    title: "Classify a record with CASE", intro: "A report should distinguish a missing amount, a large sale and a standard sale. Express that classification in a query while preserving the original amount, so a convenient label does not erase the evidence behind it.", explanation: "CASE evaluates conditions in order and returns the result of the first true branch. Handle missingness explicitly before numeric thresholds. The classification adds an output column; it does not update the input records.", code: sales + "SELECT id, amount,\n       CASE\n         WHEN amount IS NULL THEN 'missing'\n         WHEN amount >= 100 THEN 'large'\n         ELSE 'standard'\n       END AS amount_band\nFROM sales\nORDER BY id;", output: "id | amount | amount_band\n1  | 120    | large\n2  | 80     | standard\n3  | 50     | standard\n4  | NULL   | missing",
    terms: ["Condition", "CASE", "Label"], objectives: ["Write an ordered classification.", "Keep missingness distinct from a numeric band.", "Retain the original value beside a derived label."], nodes: ["The original amount remains in the result for inspection.", "CASE first checks NULL, then the large-sale threshold.", "The report adds a label without changing the underlying record."], steps: ["Add a sale with amount exactly 100 and predict its band.", "Change the threshold to 80 and identify every changed row.", "Remove the NULL branch temporarily and explain the misleading standard label for Chen."], activity: "Classify orders as paid, awaiting payment or unknown status. Keep the status field beside the label and test NULL explicitly.", mistakes: ["Letting a broad ELSE hide missing information.", "Assuming a classification writes back to the database.", "Discarding the input value that explains a label."], summary: ["CASE branch order is part of the rule.", "Missing values need a deliberate classification.", "Derived labels should remain traceable to original fields."], check: { prompt: "Why does the missing-value branch come first?", options: ["CASE cannot compare numbers", "NULL equals zero", "The report needs an explicit missing category", "CASE always executes every branch"], answer: 2, explanation: "Without an explicit NULL branch, the unknown amount can fall into ELSE and be labelled as if it were a known standard amount." }, source: source("Conditional expressions", "functions-conditional"),
  },
  7: {
    title: "Break an analysis into named query stages", intro: "Make a paid-sales summary easier to inspect by giving its filtered records a name. Use a common table expression to separate row selection from customer aggregation, then check each stage before extending the query.", explanation: "A CTE introduced with WITH names a query for use in the current statement. It is a readability tool, not a promise that a permanent table or a particular execution plan will be created.", code: sales.slice(0, -1) + ", paid AS (\n  SELECT customer, amount FROM sales WHERE status = 'paid'\n)\nSELECT customer, SUM(amount) AS known_paid_total\nFROM paid\nGROUP BY customer\nORDER BY customer;", output: "customer | known_paid_total\nAmina    | 120\nBrian    | 50\nChen     | NULL",
    terms: ["Fixture", "CTE", "Summary"], objectives: ["Name an intermediate query.", "Separate filtering from summarising.", "Inspect a stage without assuming materialisation."], nodes: ["The sales fixture supplies the original records.", "The paid CTE exposes only paid rows and the fields required next.", "The final SELECT aggregates that stage by customer."], steps: ["Replace the final SELECT with SELECT * FROM paid and inspect its three rows.", "Restore the summary and explain Chen's NULL result.", "Rename the CTE to paid_sales consistently and confirm the result is unchanged."], activity: "Add a named stage for known paid amounts. Compare the population and total with the original paid stage, and explain which record disappears.", mistakes: ["Treating a CTE name as a persistent database table.", "Assuming WITH guarantees faster execution.", "Changing several stages at once without comparing intermediate outputs."], summary: ["Named stages can make a query easier to explain.", "A CTE belongs to its statement.", "Inspect intermediate rows before trusting the final summary."], check: { prompt: "What does the paid CTE name in this example?", options: ["A permanent table available to every later query", "A saved file", "A database user", "A query used within this statement"], answer: 3, explanation: "The name belongs to a common table expression within the current statement. It does not create a permanent table." }, source: source("WITH queries", "queries-with"),
  },
  8: {
    title: "Compare each sale with its customer total", intro: "Sometimes a report needs every original sale and the customer's total beside it. Use a window function to preserve individual records while computing a related summary, rather than collapsing the result to one row per customer.", explanation: "A window aggregate computes across a partition while keeping each input row. Here PARTITION BY customer defines the related records. There is no window ordering, so SUM covers the entire customer partition.", code: sales + "SELECT id, customer, amount,\n       SUM(amount) OVER (PARTITION BY customer) AS customer_total\nFROM sales\nORDER BY id;", output: "id | customer | amount | customer_total\n1  | Amina    | 120    | 200\n2  | Amina    | 80     | 200\n3  | Brian    | 50     | 50\n4  | Chen     | NULL   | NULL",
    terms: ["Row grain", "Partition", "Window total"], objectives: ["Keep individual sale rows in an analytical result.", "Define a window partition.", "Distinguish a window total from a grouped result."], nodes: ["Each output row still represents one sale.", "The window groups related rows by customer for calculation only.", "Each Amina row displays the same known customer total of 200."], steps: ["Compare the four returned rows with a GROUP BY customer query.", "Add another Amina sale and predict both the row count and repeated total.", "Explain why adding ORDER BY inside OVER can change the default frame and is not a cosmetic edit."], activity: "Add COUNT(*) OVER (PARTITION BY customer) to the query. Explain why Amina's rows both show two while the result still contains four sales.", mistakes: ["Adding repeated window totals together and counting the same customer total multiple times.", "Confusing a window partition with collapsed grouped output.", "Adding window ordering without considering the frame."], summary: ["Window functions preserve input row grain.", "PARTITION BY defines related rows for the calculation.", "A repeated partition total must not be summed as if it were a row amount."], check: { prompt: "How many rows does this window query return for the four-row fixture?", options: ["Four", "Three", "One", "Two"], answer: 0, explanation: "The window function adds a value to each input row. It does not collapse the two Amina sales into one result row." }, source: source("Window functions", "tutorial-window"),
  },
  9: {
    title: "Find duplicate identifiers before reporting", intro: "A repeated sale identifier can make a report appear to contain more business events than actually occurred. Test identifier uniqueness before aggregating, and distinguish a legitimate repeated customer from an invalid repeated sale key.", explanation: "The check groups by the identifier and counts rows in each group. HAVING COUNT(*) > 1 identifies repeated keys. It finds a data-quality symptom; deciding which record is authoritative requires a documented correction policy.", code: "WITH incoming(id, customer) AS (\n  VALUES (1, 'Amina'), (1, 'Amina'), (2, 'Brian')\n)\nSELECT id, COUNT(*) AS occurrences\nFROM incoming\nGROUP BY id\nHAVING COUNT(*) > 1\nORDER BY id;", output: "id | occurrences\n1  | 2",
    terms: ["Identifier", "Grouping", "Duplicate check"], objectives: ["Check a candidate identifier for duplicates.", "Distinguish event keys from customer names.", "Avoid hiding duplicates with an unexplained DISTINCT."], nodes: ["The input contains three rows but repeats sale identifier 1.", "Grouping by the sale identifier produces a count per event key.", "The duplicate check flags key 1 for investigation before totals are trusted."], steps: ["Run the check and identify both input rows for key 1.", "Add two different customers with the same display name and explain why names are not event identifiers.", "Compare SELECT DISTINCT with the original input and explain which information it hides."], activity: "Create a fixture with one exact duplicate and one conflicting record sharing the same key. Write a query to locate the keys and describe how each case needs investigation.", mistakes: ["Treating repeated customer names as duplicated sales.", "Using DISTINCT to hide a duplicate without finding its cause.", "Deleting a conflicting row without an authoritative source."], summary: ["Uniqueness checks depend on the correct key.", "Detection does not establish which record should be retained.", "Investigate duplicate inputs before calculating event totals."], check: { prompt: "What does the repeated identifier check establish?", options: ["Which row must be deleted", "That the identifier occurs more than once", "That all amounts are correct", "That the customer is fraudulent"], answer: 1, explanation: "It detects repeated keys. It does not determine the authoritative record, the cause, or anyone's intent." }, source: source("Grouped table expressions", "queries-table-expressions"),
  },
  10: {
    title: "Reconcile included and excluded records", intro: "Before sharing a paid-sales report, account for the records it excluded. Build a small count summary that explains the original population and the status rule, so a missing record cannot be confused with a disappeared or duplicated sale.", explanation: "Conditional counts separate paid and other statuses. COUNT(CASE WHEN ... THEN 1 END) excludes the NULL returned for non-matching rows. Treat missing status as its own policy decision; this example includes it in the other-status count.", code: sales + "SELECT COUNT(*) AS all_records,\n       COUNT(CASE WHEN status = 'paid' THEN 1 END) AS paid,\n       COUNT(CASE WHEN status <> 'paid' OR status IS NULL THEN 1 END) AS other\nFROM sales;", output: "all_records | paid | other\n4           | 3    | 1",
    terms: ["Population", "Partitioned counts", "Reconciliation"], objectives: ["Account for input records under an explicit rule.", "Count matching rows with a conditional expression.", "Check that included and excluded counts sum to the population."], nodes: ["The population begins with four sales records.", "The status conditions classify each row into paid or other.", "Three paid plus one other reconciles to all four original records."], steps: ["Check the three counts by listing the four rows.", "Add a NULL status and predict all three new counts.", "Write a separate unknown-status count if the report needs that distinction, and reconcile all categories."], activity: "Create paid, pending and unknown-status categories that do not overlap. Prove that their counts sum to the source count and document any unrecognised status.", mistakes: ["Using overlapping categories and double-counting records.", "Leaving NULL status outside every category.", "Checking a total without first stating the population."], summary: ["Every input record should have an explained reporting treatment.", "Categories need explicit and non-overlapping rules.", "A reconciliation compares the report with independent source counts."], check: { prompt: "With disjoint, exhaustive categories, what should their counts sum to?", options: ["Only the paid count", "The number of distinct names", "The input population count", "Always zero"], answer: 2, explanation: "Every source row belongs to exactly one category. Their sum must equal the count of the intended input population." }, source: source("SELECT processing and grouping", "sql-select"),
  },
  11: {
    title: "Deliver a report with zero-order customers included", intro: "Finish with a report that includes every intended customer, counts paid orders and makes missing amounts visible. Preserve customers with no matching paid orders, then reconcile the result instead of presenting a table without explaining its rules.", explanation: "The paid-status condition belongs in the join so it does not remove unmatched customers. COUNT(o.id) measures matches; COUNT(o.amount) measures known amounts. A zero total below represents no known matched amount, so the missing-amount count must stay visible.", code: "WITH customers(id, name) AS (\n  VALUES (1, 'Amina'), (2, 'Brian'), (3, 'Chen')\n), orders(id, customer_id, amount, status) AS (\n  VALUES (101, 1, 120, 'paid'), (102, 1, 80, 'pending'),\n         (103, 2, NULL, 'paid')\n)\nSELECT c.name, COUNT(o.id) AS paid_orders,\n       COUNT(o.id) - COUNT(o.amount) AS missing_amounts,\n       COALESCE(SUM(o.amount), 0) AS known_paid_total\nFROM customers AS c\nLEFT JOIN orders AS o\n  ON o.customer_id = c.id AND o.status = 'paid'\nGROUP BY c.id, c.name\nORDER BY c.id;", output: "name  | paid_orders | missing_amounts | known_paid_total\nAmina | 1           | 0               | 120\nBrian | 1           | 1               | 0\nChen  | 0           | 0               | 0",
    terms: ["Population", "Matching rules", "Coverage report"], objectives: ["Preserve the complete customer population.", "Count orders and missing amounts separately.", "Explain and reconcile a final report."], nodes: ["Three customers are the required output population.", "The join matches paid orders without removing customers who have none.", "The report distinguishes zero matching orders from a matched order whose amount is missing."], steps: ["Predict each of the three output rows before running the statement.", "Move the status filter to WHERE temporarily and identify the lost customer; then restore it.", "Reconcile two paid orders, one missing amount and a known paid total of 120 against the source."], activity: "Complete the course project with a fourth customer and another paid order. Include the input fixture, expected table, result, missing-data policy and a short reconciliation note.", mistakes: ["Moving a right-table filter to WHERE and losing unmatched customers.", "Calling Brian's displayed zero a confirmed zero-value sale.", "Sharing a report without its population, status rule or coverage."], summary: ["Keep population-preserving filters in the intended join boundary.", "Show missing-value coverage beside substituted totals.", "A report is ready to explain only when its counts and known amounts reconcile."], check: { prompt: "Why does Brian's displayed total of zero need the missing_amounts column?", options: ["Brian has no customer record", "The query deleted his order", "Every amount was verified as zero", "His paid order has an unknown amount, not a confirmed zero amount"], answer: 3, explanation: "COALESCE supplies a display default for the absent known total. missing_amounts prevents that zero from being mistaken for evidence of a zero-valued order." }, source: source("Joins between tables", "tutorial-join"),
  },
};
