import type { Lesson, LessonVisual } from "../learning-types";

function diagram(lesson: Lesson, title: string, items: LessonVisual["items"], takeaway: string): Pick<Lesson, "visual" | "visuals"> {
  const visual: LessonVisual = { id: `${lesson.id}-worked-concept`, kind: "flow", title, description: `${title}: a step-by-step view of the code example.`, labels: items.map(item => item.label), items, connections: ["then", "then"], placement: "after-objectives", caption: "Follow each step and compare it with the runnable example below.", takeaway };
  return { visual, visuals: [visual] };
}

export function addWorkedExample(courseId: string, concept: string, lesson: Lesson): Lesson {
  if (courseId === "python-fund" && concept === "validation") {
    lesson = { ...lesson, ...diagram(lesson, "Text to a valid quantity", [{ label: "Parse text", detail: "Convert with int(); invalid integer text raises ValueError." }, { label: "Check range", detail: "Accept only positive values; zero and negative integers fail this rule." }, { label: "Return result", detail: "Return the accepted quantity, or None for an invalid entry." }], "Successful parsing does not establish business validity."), commonMistakes: ["Catching every exception and hiding a programming defect.", "Assuming that a negative integer cannot be parsed.", "Testing only valid quantities and skipping zero or blank input."], summary: ["Handle the conversion error you expect.", "Validate the allowed range after parsing.", "Retain tests for conversion failures and range boundaries."] };
    return { ...lesson, title: "Validate a whole-number input in Python", introduction: "A delivery form needs a positive whole-number quantity. Learn to distinguish conversion errors from values that parse successfully but break a business rule, and check both kinds of failure with repeatable examples.", objectives: ["Convert text to an integer and handle ValueError.", "Reject zero and negative quantities explicitly.", "Test valid, invalid and boundary inputs."], blocks: [
      { type: "paragraph", text: "int() converts suitable text to an integer. Conversion alone does not establish that a value is useful: '-2' parses but is not a valid order quantity. Keep the conversion handler narrow so unrelated programming defects remain visible." },
      { type: "code", language: "python", code: "def quantity(text):\n    try:\n        value = int(text)\n    except ValueError:\n        return None\n    return value if value > 0 else None\n\nfor sample in ['3', '0', '-2', 'three', '3.5']:\n    print(repr(sample), quantity(sample))" },
      { type: "table", caption: "Expected results from the quantity validator", headers: ["Input", "Result", "Reason"], rows: [["'3'", "3", "Positive integer"], ["'0'", "None", "Outside the allowed range"], ["'-2'", "None", "Negative quantity"], ["'three'", "None", "Cannot convert to an integer"], ["'3.5'", "None", "Decimal text is not integer text"]] },
      { type: "steps", title: "Test and extend the rule", items: ["Run the file with Python 3 and compare all five output lines with the table.", "Add a blank string and a value with surrounding spaces. Predict each result first.", "Add a maximum of 100 items. Test 99, 100 and 101.", "Explain why catching every exception would make debugging harder."] },
      { type: "callout", tone: "note", title: "Keep input types explicit", body: "This function accepts text. Passing None is a different programming contract and raises TypeError; do not silently catch it as a user's typing mistake." },
    ], activity: "Extend quantity() to allow 1–100 items. Keep the original five cases and add 99, 100, 101 and blank input. Save the output and explain which failures are conversion errors and which are range errors.", check: { prompt: "Why does '-2' need a check after int() succeeds?", options: ["Python cannot store negative integers", "Parsing and business validity are different checks", "ValueError always handles negative values", "Every input must become a float"], answer: 1, explanation: "Negative integers are valid Python values. The positive-quantity requirement is a separate rule that your code must enforce." }, references: [{ title: "Python language reference", organization: "Python Software Foundation", url: "https://docs.python.org/3/reference/index.html", accessed: "2026-10-07" }, { title: "Errors and exceptions", organization: "Python Software Foundation", url: "https://docs.python.org/3/tutorial/errors.html", accessed: "2026-10-07" }] };
  }
  if (courseId === "sql" && concept === "exploration") {
    lesson = { ...lesson, ...diagram(lesson, "Customers to an order-count report", [{ label: "Three customers", detail: "Amina, Brian and Chen must each appear in the final report." }, { label: "Match orders", detail: "LEFT JOIN finds two orders for Amina, one for Brian and no order for Chen." }, { label: "Count identifiers", detail: "COUNT(o.id) returns 2, 1 and 0 because it excludes the unmatched NULL." }], "Preserve the left-hand records and count only matching order identifiers."), commonMistakes: ["Using INNER JOIN and dropping customers without orders.", "Counting all joined rows with COUNT(*) instead of matching orders.", "Filtering an order field in WHERE and removing unmatched customers."], summary: ["LEFT JOIN preserves unmatched customers.", "COUNT(column) excludes NULL values.", "Check the intended row grain and predict the fixture result before extending the report."] };
    return { ...lesson, title: "Keep customers without orders in a SQL report", introduction: "A customer report must include people who have never placed an order. Build a small dataset, predict the result and see why a LEFT JOIN preserves those customers while the choice of counting expression changes the answer.", objectives: ["Explain how an inner join differs from a left join.", "Count matching orders without counting an unmatched row.", "Check query output using a small, known dataset."], blocks: [
      { type: "code", language: "sql", code: "WITH customers(id, name) AS (\n  VALUES (1, 'Amina'), (2, 'Brian'), (3, 'Chen')\n), orders(id, customer_id) AS (\n  VALUES (101, 1), (102, 1), (103, 2)\n)\nSELECT c.name, COUNT(o.id) AS order_count\nFROM customers AS c\nLEFT JOIN orders AS o ON o.customer_id = c.id\nGROUP BY c.id, c.name\nORDER BY c.id;" },
      { type: "table", caption: "Expected PostgreSQL result: one row per customer", headers: ["Customer", "order_count"], rows: [["Amina", "2"], ["Brian", "1"], ["Chen", "0"]] },
      { type: "paragraph", text: "LEFT JOIN keeps each customer even without a matching order. The unmatched order fields become NULL. COUNT(o.id) counts non-NULL order identifiers; COUNT(*) would count the preserved row and incorrectly give Chen a count of 1." },
      { type: "steps", title: "Investigate the report", items: ["Run the complete query in a PostgreSQL scratch database; it creates no permanent tables.", "Replace LEFT JOIN with INNER JOIN and identify the missing customer.", "Restore LEFT JOIN, replace COUNT(o.id) with COUNT(*) and explain Chen's result.", "Add another order for Brian and predict the changed count before running the query."] },
      { type: "callout", tone: "remember", title: "Filter without losing the unmatched rows", body: "A WHERE condition on an order field can remove the NULL rows preserved by LEFT JOIN. Decide whether the condition belongs in the join or after grouping, and test a customer with no orders." },
    ], activity: "Add a fourth customer with no orders. Produce a report showing all four customers, then a second report showing only customers with no orders. Explain your filter and retain both query outputs.", check: { prompt: "Which expression counts zero orders for an unmatched customer?", options: ["COUNT(*)", "COUNT(c.id)", "COUNT(o.id)", "COUNT(c.name)"], answer: 2, explanation: "The unmatched order identifier is NULL, which COUNT(o.id) excludes. Counting customer fields or every row would count the customer row." }, references: [{ title: "PostgreSQL SQL language guide", organization: "PostgreSQL Global Development Group", url: "https://www.postgresql.org/docs/current/sql.html", accessed: "2026-10-07" }, { title: "Joins between tables", organization: "PostgreSQL Global Development Group", url: "https://www.postgresql.org/docs/current/tutorial-join.html", accessed: "2026-10-07" }] };
  }
  return lesson;
}
